---

Lint:
  stage: Code Quality
  image: node:13-alpine
  script:
    - npx yaml-lint *.yml
    - npx prettier --check *.yml

F1 test:
  stage: Code Quality
  image: alpine:3.11
  interruptible: true
  variables:
    TRACE: "true"
    F1_ENV: testing
    #
    CONTEXT: f1_test_1
    F1_PACKAGES_FOLDER: fake_packages
    F1_CACHE_FOLDER: fake_cache
    F1_CHECK_FILES: f1/.gitkeep
  script:
    #
    - wget https://raw.github.com/tlevine/urchin/v0.0.6/urchin &&
      chmod +x urchin &&
      ./urchin -v
    #
    # NOTE(douglasduteil): add curl to the alpine container
    # curl is not optional here. It's only used for test purpose
    - apk add curl
    #
    - ./urchin f1/test
